### ISSUE TITLE
"Could not find or load main class edu.harvard.hul.ois.fits.Fits" when run from outside installation dir on Windows

### ISSUE THREAD

**Issue by mjordan** [harvard-lts/fits#62]
Despite the fix implemented in https://github.com/harvard-lts/fits/issues/10 we were still getting this error with FITS 0.9.0. Our environment is relatively complex (on a Windows VM, running a PHP script that runs another PHP script as a background process that in turn runs fits.bat), which may explain why the earlier fix didn't help us. However, one of our sysadmins (@rbos) modified fits.bat to get it working for us. Here's a diff of his fits.bat against the one shipped with 0.9.0:

```
$ diff fits.bat "fits.bat.090"
4c4
< setlocal enabledelayedexpansion
---
> setlocal
13a14,15
> cd %FITS_HOME%
>
17c19
< for %%i in (%FITS_HOME%\lib\*.jar) do set JARS=!JARS!;%%i
---
> for %%i in (lib\*.jar) do call "%FITS_HOME%\cpappend.bat" %%i
23d24
<
```

I'm not sure this fix is necessary outside the ~~byzantine~~ highly modularized way we're invoking fits.bat, but we're offering it here in case it's more generally useful.

**Comment by bitsgalore** [comment]
In addition to the report above, I'm getting this error both under Linux *and* Windows (using FITS 0.10.2). Also, the occurrence of the error is independent of the execution directory  - it also occurs if I run it from the installation dir!

**Comment by daveneiman** [comment]
It would be helpful to us if you could forward additional details as we are not having this problem in our typical deployment environment which is Linux. A pull request on the 'dev' branch proposing a fix would be even more helpful for including in a release. In that we are already testing the 1.0.0 release it would need to go into a subsequent release. Thanks!

**Comment by bitsgalore** [comment]
OK, so I did some additional tests. First of all I already tried several tweaks to the launcher scripts, but this didn't fix things.

As I remember this used to work before, I then downloaded and installed all previous FITS releases starting from 0.9.0, and tried to get them running.  FITS 0.9.0 and 0.10.0 run without errors, both on my Windows 7 and Linux (Mint 17.2, equivalent to Ubuntu 14.04.3 LTS) machines. However on both machines I'm getting the error with version 0.10.1 and 0.10.2. 

As the shell launcher and configuration scripts haven't changed between versions 0.10.0 and 0.10.1, my best guess is that the cause is *not* in the launcher scripts, but something else that changed between 0.10.0 and 0.10.1. I have no idea *what* exactly (also I'm no Java developer myself), but perhaps this information may help in narrowing things down.

**Comment by dbirtwellharvard** [comment]
Johan van der Knijff:

I just realized what your issue might be. We no longer include the FITS jar file in GitHub (we stopped this with release 0.10.1). GitHub is only for individuals wishing to build and/or modify FITS.

The official releases for FITS are available at the official FITS release page:

http://projects.iq.harvard.edu/fits/downloads

Let us know if this solves your problem.
Thanks,

dbirtwell

**Comment by dbirtwellharvard** [comment]
Closed by accident.

**Comment by bitsgalore** [comment]
Hi David,

You're right, the ZIP from the download page works, both for Linux and Windows. In fact I had come across the download page before, but I hadn't realised the zips were different ones from those hosted at Github. 

Since I imagine this may confuse other users as well: perhaps it might make some sense to host the ZIPs with the JARS on Github as well (you could do this as part of a Release). Then you could simply link to those ZIPs from the downloads page on the main site. The advantage of that would be that users would find the correct ZIPs, no matter whether their entry point is Github or the main site.

Anyway, thanks for the help. I think the issue can be closed now.

**Comment by daveneiman** [comment]
Glad to hear the issue is resolved.
We have a policy of not putting built artifacts (fits.jar, fits.zip) into source control.
However, it would be a good idea to make it clear that the "user" version of FITS is on the fitsool.org site and that the GitHub site is strictly for those interested in development.

**Comment by rbos** [comment]
I notice that the fits.bat in the main branch still doesn't have the patch in the original topic.

It's a pretty good change, I think, since it eliminates cpappend.bat entirely.

</.02>

**Comment by bitsgalore** [comment]
The artefacts that you put in a Github release are not under source control. See e.g. here how we now do this for jpylyzer:

<https://github.com/openpreserve/jpylyzer/releases/tag/1.17.0>

None of the .deb and .zip files (apart from the source archives) in this release are under any kind of version control. They're not even part of the repo; I just manually upload those files for every new release. Anyway, I understand there may be various other reasons for keeping the hosting of source and build artefacts separate.
